import 'dart:convert';

Autogenerated articlesListFromJson(String str) =>
    Autogenerated.fromJson(json.decode(str));

class Autogenerated {
  List<Articles> articles;

  Autogenerated({required this.articles});

  factory Autogenerated.fromJson(Map<String, dynamic> json) => Autogenerated(
        articles: List<Articles>.from(
            json["articles"].map((x) => Articles.fromJson(x))),
      );

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.articles != null) {
      data['articles'] = this.articles.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class Articles {
  String image;
  String title;
  String content;

  Articles({required this.image, required this.title, required this.content});

  factory Articles.fromJson(Map<String, dynamic> json) => Articles(
        image: json["image"] == null ? null : json["image"],
        title: json["title"] == null ? null : json["title"],
        content: json["content"] == null ? null : json["content"],
      );

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['image'] = this.image;
    data['title'] = this.title;
    data['content'] = this.content;
    return data;
  }
}
